### ISSUE TITLE
PR: Text orientation

### ISSUE THREAD

**Issue by ZvikaZ** [raphink/fancytabs#1]
Hi.

I've seen your 'fancytabs' package, and it looks very nice.

However, there is one small improvement that can be made (and will help me...) - if it's possible, it'd be great to have the text orientation parameterized.

The default will continue to be rotated, as it is today, but it'll be possible to have the text printed regularly, without rotating.

Thanks,
Zvika

**Comment by raphink** [comment]
Alright. I see you put "PR" in the title, but this is an issue. This is a little doc on how to create a pull request on GitHub: https://help.github.com/articles/creating-a-pull-request/

**Comment by ZvikaZ** [comment]
Please see Pull Request https://github.com/raphink/fancytabs/pull/3

**Comment by raphink** [comment]
Thanks. I'll close this as #3 is taking care of it.
