### ISSUE TITLE
PR: Tab location

### ISSUE THREAD

**Issue by ZvikaZ** [raphink/fancytabs#2]
Hi.
I think that the tab should be in the outer side of the page (and not fixed at the right side, as it is now).

Please note the 'outer side' changes, depending on the language direction.
Maybe that information can be queried from Babel or Polyglossia; or maybe it's easier to add a new parameter,  \fancytabsRTL, which can control this.

**Comment by raphink** [comment]
OK. PR welcome for that :smile:

**Comment by ZvikaZ** [comment]
I have implemented something slightly different:
- `\fancytab` macro now has optional argument for horizontal location
- the default is previous behaviour - RIGHT
- if it's LEFT - it's on the left side of the page.

The user who calls the macro is responsible for deciding whether to use LEFT or RIGHT.

Example usage:
(BTW, I'd recommend to add such example to the documentation, and also write that this package supports RTL languages)

```
\documentclass{book}

\usepackage{lipsum}

\usepackage{fancytabs}
\usepackage{fancyhdr}

\pagestyle{fancy}
\fancyhf{}
\fancyhead[LO]{\thepage\fancytab[LEFT]{I'm on the left}{\thepage}}
\fancyhead[RE]{\thepage\fancytab[RIGHT]{RIGHT}{\thepage}}

\usepackage{polyglossia}        
\setdefaultlanguage{hebrew}       
\usepackage{fontspec}
\newfontfamily\hebrewfont{Times New Roman}[Script=Hebrew]


\begin{document}

\newpage
\lipsum

\newpage
\lipsum
\end{document}
```

**Comment by raphink** [comment]
I have merged #3 and will make a release from it.

**Comment by raphink** [comment]
For some reason, the package fails to build with a recent TeXLive installation, so I'm not able to release at this point.

**Comment by ZvikaZ** [comment]
Maybe it's related to '\RequirePackage{etoolbox}' that I added later?

What error did you get?

2016-03-29 12:02 GMT+03:00 Raphaël Pinson notifications@github.com:

**Comment by raphink** [comment]
I doesn't seem like it. This is the error:

```
***************************
* Character table correct *
***************************

! Package tikz Error: Sorry, some package has redefined the meaning of the math
-mode dollar sign. This is incompatible with tikz and its calc library and migh
t cause unrecoverable errors.

See the tikz package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.145 % \end{verbatim}

? 
```

but I can't find any useful information (besides hacks to make it stop) on what causes this really...

**Comment by ZvikaZ** [comment]
And without my changes, is it working?

2016-03-29 12:38 GMT+03:00 Raphaël Pinson notifications@github.com:

**Comment by raphink** [comment]
No, it doesn't work either. It's apparently a problem with the new TikZ. My Travis CI build works though, so it seems to be the TeXLive version shipped with Ubuntu 15.10.

**Comment by ZvikaZ** [comment]
OK then, at least I didn't break anything :)

Googling doesn't give clues?

Maybe you can try using alternate source of TexLive:
https://help.ubuntu.com/community/LaTeX

Anyway, for me it's not urgent, so it's your decision if you prefer to just
wait a few days for a possible fix.

2016-03-29 12:57 GMT+03:00 Raphaël Pinson notifications@github.com:

**Comment by ZvikaZ** [comment]
Hi.

Any updates?

Thanks

2016-03-29 13:12 GMT+03:00 צביקה הרמתי haramaty.zvika@gmail.com:

**Comment by ZvikaZ** [comment]
Hi.

When you have time, it'd be great to get some update on this...

Thanks

**Comment by raphink** [comment]
Hi @ZvikaZ 

I just submitted the package to the CTAN.

**Comment by raphink** [comment]
@ZvikaZ https://lists.dante.de/pipermail/ctan-ann/2016-June/009553.html

**Comment by ZvikaZ** [comment]
Great!
Thanks.
